apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jambonz
  name: pod-reader-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "endpoints", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
