# mysql configuration
mysql: 
  image: mysql:5.7
  host: mysql 
  database: jambones
  user: jambones_user
  storage: 10Gi
  # if empty, an empty password is used for the root user using MYSQL_ALLOW_EMPTY_PASSWORD
  rootSecret: dWdlUFdxbTluQDZCVkBDdyUzb1ZEcFppczI1WFVeUWlhWTg=
  secret: Y2Q0YmExMTQ1ZDg2N2Y2ZTU3MzQ=
  podAnnotations:

# redis configuration used by Node.js app that need to connect
redis: 
  image: redis:alpine
  host: redis 
  port: "6379"
  podAnnotations:

# Storage Class definition for the StatefulSet
storageClassName:

# Affinity
affinity:

dbcreate:
  sipDomain: prod-worker4.dialytica.com
  baseIvrApiUrl: http://ivr-app:8476/api/v1
  image: sptmru/jambonz-db-create:0.27
  jambonzAccountSid: a012c987-a123-2ccd-bb88-d456e567f678
  jambonzApplicationSid: 55123cc2-3456-4d56-88ac-2aa4f0fd93a9
  jambonzApiKey: 3d9108c8-166e-4473-bebd-8a99e94a12a6

fs-status:
  redis:
    image: redis:7.2.5