# mysql configuration
mysql: 
  image: mysql:5.7
  host: mysql 
  database: jambones
  user: jambones 
  storage: 10Gi
  # if empty, an empty password is used for the root user using MYSQL_ALLOW_EMPTY_PASSWORD
  rootSecret:
  secret: amFtYm9uZXM=
  podAnnotations:

# redis configuration used by Node.js app that need to connect
redis: 
  image: redis:alpine
  host: redis 
  port: "6379"
  podAnnotations:

# Storage Class definition for the StatefulSet
storageClassName:

# Affinity
affinity:

dbcreate:
  sipDomain: sip.jambonz.sptm.space
  baseIvrApiUrl: http://ivr-app-dev.sptm.space
  image: sptmru/jambonz-db-create:0.26
  jambonzAccountSid: a012c987-a123-2ccd-bb88-d456e567f678
  jambonzApplicationSid: 55123cc2-3456-4d56-88ac-2aa4f0fd93a9
  jambonzApiKey: 3d9108c8-166e-4473-bebd-8a99e94a12a6

ivrapp:
  redis:
    image: redis/redis-stack-server:7.2.0-v10