# mysql configuration
mysql: 
  image: mysql:5.7
  host: mysql 
  database: jambones
  user: jambones 
  storage: 10Gi
  # if empty, an empty password is used for the root user using MYSQL_ALLOW_EMPTY_PASSWORD
  rootSecret:
  secret: amFtYm9uZXM=
  podAnnotations:

# redis configuration used by Node.js app that need to connect
redis: 
  image: redis:alpine
  host: redis 
  port: "6379"
  podAnnotations:

# Storage Class definition for the StatefulSet
storageClassName:

# Affinity
affinity:

dbcreate:
  sipDomain: sip.jambonz.sptm.space
  baseIvrApiUrl: http://ivr-app-dev.sptm.space
  image: sptmru/jambonz-db-create:latest
  jambonzAccountSid: x012y987-a123-b234-c345-d456e567f678
  jambonzApplicationSid: 3d9108c8-166e-4473-bebd-8a99e94a12a6
  jambonzApiKey: 3d9108c8-166e-4473-bebd-8a99e94a12a6