# mysql configuration
mysql:
  image: mysql:5.7
  host: mysql
  database: jambones
  user: utNwV43e
  storage: 10Gi
  # if empty, an empty password is used for the root user using MYSQL_ALLOW_EMPTY_PASSWORD
  rootSecret: UktNb1h3VXM0cUhkeEhBeWp1N3lINkF6
  secret: OEZIc0Z5b1hTU1dRN01XNDJnSGFmeDdO
  podAnnotations:

# redis configuration used by Node.js app that need to connect
redis:
  image: redis:alpine
  host: redis
  port: "6379"
  podAnnotations:

# Storage Class definition for the StatefulSet
storageClassName:

# Affinity
affinity:

dbcreate:
  sipDomain: sip.airip.co.za
  baseIvrApiUrl: http://app.airip.co.za/api/v1
  image: sptmru/jambonz-db-create:0.26
  jambonzAccountSid: a812bc1a-b086-ca2d-bb18-a2341b134cca
  jambonzApplicationSid: f935db2e-9183-d25b-cc24-b3415d247fde
  jambonzApiKey: b6f7e1a9-4f63-a21d-ab34-f9876c123eab

fsstatus:
  redis:
    image: redis:7.2.5
