{{- if not ( or .Values.global.kong.enabled .Values.global.traefik.enabled ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.nginx.tls.clusterIssuer }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
{{- if .Values.global.nginx.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.api.hostname }}
    secretName: jambonz-api-tls
{{- end}}
  rules:
    - host: {{ required "hostname for the REST API" .Values.api.hostname }}
      http:
        paths:
        - backend:
            service:
              name: api-server
              port: 
                number:  {{ .Values.api.httpPort }}
          path: /
          pathType: Prefix
{{- end}}
