apiVersion: v1
kind: Service
metadata:
  labels:
    app: fs-status-api
{{ include "common.labels" . | indent 4 }}
  name: fs-status-api
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "fs-status-api-http"
      port: {{ default "8479" .Values.fs-status-api.httpPort }}
      targetPort:  {{ default "8479" .Values.fs-status-api.httpPort }}
  selector:
    app: fs-status-api
