apiVersion: v1
kind: Service
metadata:
  labels:
    app: ivr-app
{{ include "common.labels" . | indent 4 }}
  name: ivr-app
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "ivr-app-http"
      port: {{ default "8476" .Values.ivrapp.httpPort }}
      targetPort:  {{ default "8476" .Values.ivrapp.httpPort }}
    - name: "ivr-app-ws"
      port: {{ default "8081" .Values.ivrapp.ws.port }}
      targetPort:  {{ default "8081" .Values.ivrapp.ws.port }}
  selector:
    app: ivr-app
