apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ivr-app
{{ include "common.labels" . | indent 4 }}
  name: ivr-app
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ default 1 .Values.ivrapp.replicas }}
  selector:
    matchLabels:
      app: ivr-app
  template:
    metadata:
      labels:
        app: ivr-app
      annotations:
        {{- if .Values.global.podAnnotations }}
        {{ toYaml .Values.global.podAnnotations | default "" | nindent 8 }}
        {{- end }}
        {{- if .Values.ivrapp.podAnnotations }}
        {{ toYaml .Values.ivrapp.podAnnotations | default "" | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.affinity }}
      affinity:
        {{ toYaml .Values.global.affinity | default "" | nindent 8 }}
      {{- end }}
      {{- if .Values.ivrapp.nodeSelector }}
      nodeSelector:
        {{ .Values.ivrapp.nodeSelector.label }}: {{ .Values.ivrapp.nodeSelector.value | quote }}      
      {{- end }}
      containers:
        - name: ivr-app
          image: {{ .Values.ivrapp.image }}
          imagePullPolicy: {{ .Values.ivrapp.imagePullPolicy }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.ivrapp.httpPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.ivrapp.httpPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
            timeoutSeconds: 5
          env:
            - name: LOG_LEVEL
              value: {{ default "info" .Values.ivrapp.logLevel  | quote }}
            - name: LOG_TO_FILE
              value: "false"
            - name: SENTRY_DSN
              value: {{ default "" .Values.ivrapp.sentry.dsn  | quote }}
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: {{ default "1.0" .Values.ivrapp.sentry.tracesSampleRate  | quote }}
            - name: SENTRY_PROFILES_SAMPLE_RATE
              value: {{ default "1.0" .Values.ivrapp.sentry.profilesSampleRate  | quote }}
            - name: SENTRY_LOG_LEVEL
              value: {{ default "error" .Values.ivrapp.sentry.logLevel  | quote }}
            - name: SENTRY_AUTH_TOKEN
              value: {{ default "" .Values.ivrapp.sentry.authToken  | quote }}
            - name: HTTP_HOSTNAME
              value: {{ printf "http://%s" (default "localhost" .Values.ivrapp.hostname) | quote }}
            - name: HTTP_PORT
              value: {{ default "8476" .Values.ivrapp.httpPort  | quote }}
            - name: API_BASE_PREFIX
              value: {{ default "/api/v1" .Values.ivrapp.apiBasePrefix  | quote }}
            - name: API_AUTH_TOKEN
              value: {{ default "" .Values.ivrapp.apiAuthToken  | quote }}
            - name: JAMBONZ_ACCOUNT_SID
              value: {{ default "" .Values.ivrapp.jambonz.accountSid  | quote }}
            - name: JAMBONZ_APPLICATION_SID
              value: {{ default "" .Values.ivrapp.jambonz.applicationSid  | quote }}
            - name: JAMBONZ_API_KEY
              value: {{ default "" .Values.ivrapp.jambonz.apiKey  | quote }}
            - name: JAMBONZ_BASE_URL
              value: {{ default "" .Values.ivrapp.jambonz.baseUrl  | quote }}
            - name: JAMBONZ_CALLBACK_BASE_URL
              value: {{ default "" .Values.ivrapp.jambonz.callbackBaseUrl  | quote }}
            - name: JAMBONZ_SIP_REALM
              value: {{ default "" .Values.ivrapp.jambonz.sipRealm  | quote }}
            - name: JAMBONZ_AMD_THRESHOLD_WORD_COUNT
              value: {{ default "4" .Values.ivrapp.jambonz.amd.thresholdWordCount  | quote }}
            - name: JAMBONZ_AMD_NO_SPEECH_TIMEOUT
              value: {{ default "5000" .Values.ivrapp.jambonz.amd.noSpeechTimeout  | quote }}
            - name: JAMBONZ_AMD_DECISION_TIMEOUT
              value: {{ default "40000" .Values.ivrapp.jambonz.amd.decisionTimeout  | quote }}
            - name: JAMBONZ_AMD_TONE_TIMEOUT
              value: {{ default "40000" .Values.ivrapp.jambonz.amd.toneTimeout  | quote }}
            - name: JAMBONZ_AMD_GREETING_COMPLETION_TIMEOUT
              value: {{ default "2000" .Values.ivrapp.jambonz.amd.greetingCompletionTimeout  | quote }}
            - name: RABBITMQ_URI
              value: {{ default "" .Values.ivrapp.rabbitmq.uri  | quote }}
            - name: RABBITMQ_CALLS_QUEUE
              value: {{ default "calls_queue" .Values.ivrapp.rabbitmq.callsQueue  | quote }}
            - name: RABBITMQ_CALL_STATUS_QUEUE
              value: {{ default "call_status_queue" .Values.ivrapp.rabbitmq.callStatusQueue  | quote }}
            - name: RABBITMQ_PREFETCH_COUNT
              value: {{ default "10" .Values.ivrapp.rabbitmq.prefetchCount  | quote }}
            - name: RABBITMQ_RECONNECT_TIMEOUT_MS
              value: {{ default "5000" .Values.ivrapp.rabbitmq.reconnectTimeout  | quote }}
            - name: RABBITMQ_USER
              value: {{ default "" .Values.ivrapp.rabbitmq.user  | quote }}
            - name: RABBITMQ_PASSWORD
              value: {{ default "" .Values.ivrapp.rabbitmq.password  | quote }}
            - name: RABBITMQ_ERLANG_COOKIE
              value: {{ default "" .Values.ivrapp.rabbitmq.erlangCookie  | quote }}
            - name: REDIS_URI
              value: "redis://ivrapp-redis.{{ default .Release.Namespace .Values.global.db.namespace }}:6379"
            - name: REDIS_JSON_TYPE
              value: {{ default "calldetails" .Values.ivrapp.redis.jsonType  | quote }}
            - name: CALL_STATUS_API_BASE_URL
              value: {{ default "" .Values.ivrapp.callStatusApi.baseUrl  | quote }}
            - name: DTMF_GATHER_TIMEOUT
              value: {{ default "15" .Values.ivrapp.dtmfGatherTimeout | quote }}
          ports:
            - containerPort: {{ default "8476" .Values.ivrapp.httpPort }}
          resources: {}
      restartPolicy: Always