apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbc-smpp
{{ include "common.labels" . | indent 4 }}
  name: sbc-smpp
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: smpp
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: jambonz-sbc-sip
  clusterIP: None
