{{- if not ( or .Values.global.kong.enabled .Values.global.traefik.enabled ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.nginx.tls.clusterIssuer }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:

{{- if .Values.global.nginx.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.webapp.hostname }}
    secretName: jambonz-webapp-tls
{{- end}}
  rules:
    - host: {{ required "hostname for the web port" .Values.webapp.hostname }}
      http:
        paths:
        - backend:
            service:
              name: webapp
              port: 
                number: 3001
          path: /
          pathType: Prefix
{{- end}}
