{{- if not ( or .Values.global.kong.enabled .Values.global.traefik.enabled ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer-webapp
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.nginx.tls.clusterIssuer }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
{{- if .Values.global.nginx.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.homer.hostname }}
    secretName: jambonz-homer-tls
{{- end}}
  rules:
    - host: {{ required "hostname for the homer portal" .Values.homer.hostname }}
      http:
        paths:
        - backend:
            service:
              name: homer-webapp
              port: 
                number: 80
          path: /
          pathType: Prefix
{{- end}}
